#ifndef CONFIG_FILE_H
#define CONFIG_FILE_H

static const char* CONFIG_FILE[] = {
    "[Global]",
    "  # node name (not include optional part)",
    "  NodeBase 'iqn.1991-05.bbx'",
    "",
    "  # socket I/O timeout sec. (polling is infinity)",
    "  Timeout 30",
    "  # NOPIN sending interval sec.",
    "  NopInInterval 20",
    "",
    "  # authentication information for discovery session",
    "  DiscoveryAuthMethod Auto",
    "",
    "  # reserved maximum connections and sessions",
    "  # NOTE: iSCSI boot is 2 or more sessions required",
    "  MaxSessions 32",
    "  MaxConnections 8",
    "",
    "  # maximum number of sending R2T in each connection",
    "  # actual number is limited to QueueDepth and MaxCmdSN and ExpCmdSN",
    "  # 0=disabled, 1-256=improves large writing",
    "  MaxR2T 64",
    "",
    "  # iSCSI initial parameters negotiate with initiators",
    "  # NOTE: incorrect values might crash",
    "  MaxOutstandingR2T 16",
    "  DefaultTime2Wait 2",
    "  DefaultTime2Retain 60",
    "  FirstBurstLength 262144",
    "  MaxBurstLength 1048576",
    "  MaxRecvDataSegmentLength 262144",
    "",
    "[PortalGroup1]",
    "  # Portal Label(not used) IP(IPv6 or IPv4):Port",
    "  #Portal DA1 [::]:3260",
    "  Portal DA1 127.0.0.1:3260",
    "",
    "[InitiatorGroup1]",
    "  Comment 'Initiator Group1'",
    "  # name with ! deny login/discovery",
    "  #InitiatorName '!iqn.1991-05.com.microsoft:moon'",
    "  # spetified name allow login/discovery",
    "  #InitiatorName 'iqn.1991-05.com.microsoft:saturn'",
    "  # special word 'ALL' match all of initiators",
    "  InitiatorName 'ALL'",
    "  Netmask 0.0.0.0/0",
    "",
    "# TargetName, Mapping, UnitType, LUN0 are minimum required",
    "[LogicalUnit1]",
    "  # full specified iqn (same as below)",
    "  # short specified non iqn (will add NodeBase)",
    "  TargetName iqn.1991-05.bbx:root0",
    "  Mapping PortalGroup1 InitiatorGroup1",
    "  # accept both CHAP and None",
    "  AuthMethod Auto",
    "  #UseDigest Header Data",
    "  UseDigest Auto",
    "  UnitType Disk",
    "  # SCSI INQUIRY - Vendor(8) Product(16) Revision(4) Serial(16)",
    "  #UnitInquiry 'FreeBSD' 'iSCSI Disk' '0123' '10000001'",
    "  # Queuing 0=disabled, 1-255=enabled with specified depth.",
    "  QueueDepth 128",
    "",
    "  # LogicalVolume for this unit on LUN0",
    "  # for file extent",
    "  LUN0 Storage ./test.img 21474836470",
    "",
    "  # for 3.5inch, 7200rpm HDD",
    "  # RPM 0=not reported, 1=non-rotating(SSD), n>1024 rpm",
    "  LUN0 Option RPM 15000",
    "  # FormFactor 0=not reported, 1=5.25, 2=3.5, 3=2.5, 4=1.8, 5=less 1.8 "
    "inch",
    "  LUN0 Option FormFactor 2",
    "",
    "  # for 2.5inch, SSD",
    "  #LUN0 Option RPM 1",
    "  #LUN0 Option FormFactor 3",
};

#endif  // CONFIG_FILE_H
